### ISSUE TITLE
procedural scene data generation 

### ISSUE THREAD

**Issue by Sjey-Lyn** [NVlabs/cabi_net#2]
Dear author.

Thank you for your awesome work,When is the code about procedural scene data generation expected to be release?

**Comment by newuhe** [comment]
Also wondering the timeline for releasing the code for training.

**Comment by adithyamurali** [comment]
Hi, this is currently not being planned.

**Comment by adithyamurali** [comment]
The code for the procedural scene generation has been released: https://github.com/NVlabs/scene_synthesizer

**Comment by bbbbbbbbly** [comment]
how to train, will this release?

**Comment by adithyamurali** [comment]
The train script is actually already available: https://github.com/NVlabs/cabi_net/blob/main/examples/train_collision_prediction.py
but it is not supported.

the crucial thing left is to write the logic for generating procedural scenes given a set of object assets and using that during training. We actually used [scene synthesizer](https://github.com/NVlabs/scene_synthesizer) to generate these procedural scenes, which was just released publicly earlier this year.
